#!/bin/bash
# install web app in dev container

cd /workspace

# install web app dependencies:
npm install --force

# install helper script dependencies:
pip install -r ./configure_build_serve/requirements.txt