#!/bin/bash
# install web app in dev container

cd /workspace

# install web app dependencies:
yarn install

# install helper script dependencies:
pip install -r ./configure_build_serve/requirements.txt
