#!/bin/bash
# start web app using the development server

# By changing into the `.devcontainer` dir,
# the `.devcontainer/.metadata-catalogue.config` file will be automatically
# used as configuration source:
cd /workspace/.devcontainer

# start development server
../configure_build_serve/run.py --dev
