version: "3"

services:
  # metadata_catalog

  metadata_catalog:
    image: ghga/metadata-catalog:main
    environment:
      METADATA_CATALOG_HOST: 0.0.0.0
      METADATA_CATALOG_PORT: 8080
    ports:
      - 8000:8080
    depends_on:
      - metadata_search_svc
      - metadata_rep

  # metadata search

  metadata_search_svc:
    image: ghga/metadata-search-service:main
    environment:
      METADATA_SEARCH_SERVICE_HOST: 0.0.0.0
      METADATA_SEARCH_SERVICE_PORT: 8080
      METADATA_SEARCH_SERVICE_CORS_ALLOWED_ORIGINS: '["*"]'
      METADATA_SEARCH_SERVICE_CORS_ALLOW_CREDENTIALS: "true"
      METADATA_SEARCH_SERVICE_CORS_ALLOWED_METHODS: '["*"]'
      METADATA_SEARCH_SERVICE_CORS_ALLOWED_HEADERS: '["*"]'
      METADATA_SEARCH_SERVICE_LOG_LEVEL: debug
      METADATA_SEARCH_SERVICE_DB_URL: mongodb://metadata_db:27017
      METADATA_SEARCH_SERVICE_DB_NAME: metadata-catalog
    entrypoint: ["sh", "-c"]
    command: |
      '''
      # install additional deps as they are needed for the population script;
      cd /service
      pip install ".[all]"

      # run the service:
      metadata-search-service
      '''
    ports:
      - 8001:8080
    depends_on:
      - metadata_db

  # metadata population

  metadata_pop:
    image: ghga/metadata-populate-job:main
    environment:
       CATALOG_DB_NAME: metadata-catalog
       CATALOG_DB_URL: mongodb://metadata_db:27017
    entrypoint: [ "bash", "-c", "./clean-catalog.sh && ./populate-catalog.sh" ]
    env_file:
     - local.env
    depends_on:
      - metadata_db 

  #metadata repo

  metadata_rep:
    image: ghga/metadata-repository-service:main
    environment:
      METADATA_REPOSITORY_SERVICE_HOST: 0.0.0.0
      METADATA_REPOSITORY_SERVICE_PORT: 8080
      METADATA_REPOSITORY_SERVICE_CORS_ALLOWED_ORIGINS: '["*"]'
      METADATA_REPOSITORY_SERVICE_CORS_ALLOW_CREDENTIALS: "true"
      METADATA_REPOSITORY_SERVICE_CORS_ALLOWED_METHODS: '["*"]'
      METADATA_REPOSITORY_SERVICE_CORS_ALLOWED_HEADERS: '["*"]'
      METADATA_REPOSITORY_SERVICE_LOG_LEVEL: debug
      METADATA_REPOSITORY_SERVICE_DB_URL: mongodb://metadata_db:27017
      METADATA_REPOSITORY_SERVICE_DB_NAME: metadata-catalog

    entrypoint: ["metadata-repository-service"]

    ports:
      - 8002:8080
    depends_on:
      - metadata_db
    env_file:
      - local.env

  # mongo db

  metadata_db:
    image: mongo:5.0.4
    volumes:
      - metadata_db_fs:/data/db
    ports:
      - 27000:27017

volumes:
  metadata_db_fs: {}
